### ISSUE TITLE
Code block moves off screen in editor

### ISSUE THREAD

**Issue by goetzk** [FlipperPA/wagtailcodeblock#10] opened 2017-12-10 09:18 UTC
Hi,
I have just tried to use wagtailcodeblock 0.3.1 in my wagtail site and the frontend bit appears to be fine when I preview.
Unfortunately, when I saved the code the Language selected and code input boxes 'jumped' to the right and now I'm unable to access various parts of the editing UI including adding/removing blocks.

The problem occurs in both Safari, Chrome and Firefox on macOS 10.13.1.

![screenshot of wagtail code block bug](https://user-images.githubusercontent.com/8732490/33803545-055b64d2-dde7-11e7-8407-241cfa131b00.png)

Is there any other information you need from me to try and figure out what is going wrong?

**Comment by FlipperPA** [comment] 2017-12-11 01:47
Howdy! Thanks for the ticket. Could you include the code for the `StreamField` you're using this in so I can try to reproduce it? Actually, for the entire `Page` model you're using? I'm trying to figure out if the field above the `CodeBlock` might be doing something funky with the CSS as well (where is says 'Running tests')? We may need to look at the entire HTML source of the page to see if there's a missing closing `</div>` or something liek that as well. It basically looks like something in your browser is pushing the entire width of the main content entire to be really, really wide.

Here's an example of a `StreamBlock` with a `CodeBlock` inside:

https://github.com/FlipperPA/wagtailcontentstream/blob/master/wagtailcontentstream/blocks.py#L37

**Comment by goetzk** [comment] 2017-12-11 02:49
You're right, that would have been smart to include :|

The diff showing what I added when setting up the field:
```
diff --git a/blog/models.py b/blog/models.py
index 08fa2f9..141c1f2 100644
--- a/blog/models.py
+++ b/blog/models.py
@@ -20,6 +20,8 @@ from wagtail.wagtailsnippets.models import register_snippet
 from wagtail.wagtailsnippets.edit_handlers import SnippetChooserPanel
 from django.utils.encoding import python_2_unicode_compatible
 
+# https://github.com/FlipperPA/wagtailcodeblock
+from wagtailcodeblock.blocks import CodeBlock
 
 from modelcluster.fields import ParentalKey
 from modelcluster.contrib.taggit import ClusterTaggableManager
@@ -112,6 +114,8 @@ class BlogPage(Page):
     body = StreamField([
         ('heading', blocks.CharBlock(classname="full title")),
         ('paragraph', blocks.RichTextBlock()),
+        ('raw_html', blocks.RawHTMLBlock()),
+        ('code_block', CodeBlock()),
         ('image', ImageChooserBlock()),
         ('file', DocumentChooserBlock()),
     ])
diff --git a/karlsblog/settings/base.py b/karlsblog/settings/base.py
index fb761a4..f2cb9ab 100644
--- a/karlsblog/settings/base.py
+++ b/karlsblog/settings/base.py
@@ -52,6 +52,7 @@ INSTALLED_APPS = [
     'django.contrib.staticfiles',
 
     'blog',
+    'wagtailcodeblock',
 ]
 
 MIDDLEWARE = [
```

And my full page model:

```
class BlogPage(Page):
    body = StreamField([
        ('heading', blocks.CharBlock(classname="full title")),
        ('paragraph', blocks.RichTextBlock()),
        ('raw_html', blocks.RawHTMLBlock()),
        ('code_block', CodeBlock()),
        ('image', ImageChooserBlock()),
        ('file', DocumentChooserBlock()),
    ])
    content_panels = Page.content_panels + [
        StreamFieldPanel('body'),
    ]
```

I have just commented out raw_html and I still see the same behaviour so it is less likely to be caused by that block.

thanks,
kk

**Comment by FlipperPA** [comment] 2017-12-17 01:37
Just an update, I'm busy doing work getting packages ready for Wagtail 2.0, but will have some time to look at this soon. Apologies for the delay.

**Comment by FlipperPA** [comment] 2018-01-18 17:15
I finally got some time to look at this, and I think I may know what's going on. The line in your screen shot starting with `api_xml = "...."` is causing the div containing the code block to get pushed to the right, as it doesn't do a line break so the code can be copied.

I think the solution here is to make that div scrollable. I'll take a look into it. Thanks for the report!

**Closed as completed** 2021-10-21 20:20 UTC
